### PR TITLE
added : notFound Page

### PR DESCRIPTION
**Pull request by Mikey1233**
Fixes: #40

## Description

I created a new page for the not-match component . NO dependencies was required for this change

## Feature Link:

---

## Screenshots:
Screenshot 2024-12-01 071953

---

## 📢 Notes for Reviewers
Add any additional information or context for the reviewers.

### CODE REVIEW

**Review by tianchengc — APPROVED** [review]
Looks good to me

**Comment by ericmaic** [comment]
It looks good. Indeed, we need a 404 page, which wasn't included in the wireframe design. Please add the header and footer layouts to see the overall effect. Also, please use the standard button design as referenced in the wireframe. Thanks!

**Comment by tianchengc** [comment]
> It looks good. Indeed, we need a 404 page, which wasn't included in the wireframe design. Please add the header and footer layouts to see the overall effect. Also, please use the standard button design as referenced in the wireframe. Thanks!

Agreed, @Mikey1233 could you refer to the wireframe and apply the styling so that it is consistent with the rest of the pages
and make the page in between header and footer

**Comment by Mikey1233** [comment]
> It looks good. Indeed, we need a 404 page, which wasn't included in the wireframe design. Please add the header and footer layouts to see the overall effect. Also, please use the standard button design as referenced in the wireframe. Thanks!

I considered that, but the developer working on the header and footer layout hasn't completed it yet.

**Comment by Mikey1233** [comment]
> > It looks good. Indeed, we need a 404 page, which wasn't included in the wireframe design. Please add the header and footer layouts to see the overall effect. Also, please use the standard button design as referenced in the wireframe. Thanks!
> 
> Agreed, @Mikey1233 could you refer to the wireframe and apply the styling so that it is consistent with the rest of the pages and make the page in between header and footer

This will certainly be implemented.

**Comment by tianchengc** [comment]
> > It looks good. Indeed, we need a 404 page, which wasn't included in the wireframe design. Please add the header and footer layouts to see the overall effect. Also, please use the standard button design as referenced in the wireframe. Thanks!
> 
> I considered that, but the developer working on the header and footer layout hasn't completed it yet.

@Mikey1233 fyi header and footer were implemented already, your dev branch might be behind latest main branch, recommend give it a git fetch and git pull —rebase origin main, you will see header and footer

**Comment by Mikey1233** [comment]
Okay, I'll check it out

**Review by tianchengc — APPROVED** [review]

**Pull request merged**
