### PR TITLE
Progress swap

### PR DESCRIPTION
**Pull request by swapnils118**
Fixes: #35 

## Description
- Performance measure added to page layout. 
- CSS modified for performance measure w.r.t design
- Background-Color added for Page.

## Feature Link:
- Progress block

## Description:
Progress block added to page.

---

## Screenshots:
ProgressComponent

---

## 📢 Notes for Reviewers
Add any additional information or context for the reviewers.

### CODE REVIEW

**Review by oveed — APPROVED** [review]
LGTM, good job

**Comment by tianchengc** [comment]
@swapnils118 could you fix merge conflict, thanks.

**Review by Mikey1233 — COMMENTED** [review]
looks okay to me

**Review by Mikey1233 — APPROVED** [review]

**Comment by swapnils118** [comment]
@tianchengc Yes I am working towards it. Will push the resolved commit in some time.

**Comment by swapnils118** [comment]
Done fixing the conflicts. Can you kindly check again @tianchengc 
Thanks

**Pull request merged**
